# Generated by Django 3.2.13 on 2022-11-05 23:51

import adoorback.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters (alphabet & 한글), digits and _ only.', max_length=20, unique=True, validators=[adoorback.validators.AdoorUsernameValidator()], verbose_name='username'),
        ),
    ]
