# Generated by Django 3.2.13 on 2022-12-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '남성'), (1, '여성'), (2, '기타')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
