# Generated by Django 3.2.13 on 2022-12-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', '영어'), ('ko', '한국어')], default='ko', max_length=10),
        ),
    ]
