# Generated by Django 3.2.13 on 2023-02-12 06:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=account.models.OverwriteStorage(), upload_to=account.models.to_profile_images),
        ),
    ]
