# Generated by Django 3.2.13 on 2023-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어')], default='ko', max_length=10),
        ),
    ]
