# Generated by Django 3.2.13 on 2022-12-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221218_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.IntegerField(choices=[(0, '미국 원주민/알래스카 원주민 (American Indian/Alaska Native'), (1, '아시아인 (Asian)'), (2, '흑인/아프리카계 미국인 (Black/African American)'), (3, '히스패닉/라틴계 미국인 (Hispanic/Latino)'), (4, '하와이 원주민/다른 태평양 섬 주민 (Native Hawaiian/Other Pacific Islander'), (5, '백인 (White)')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '여성'), (1, '남성'), (2, '트랜스젠더 (transgender)'), (3, '논바이너리 (non-binary/non-conforming)'), (4, '응답하고 싶지 않음')], null=True),
        ),
    ]
