# Generated by Django 3.2.13 on 2023-02-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221218_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.IntegerField(choices=[(0, '미국 원주민/알래스카 원주민 (American Indian/Alaska Native)'), (1, '아시아인 (Asian)'), (2, '흑인/아프리카계 미국인 (Black/African American)'), (3, '히스패닉/라틴계 미국인 (Hispanic/Latino)'), (4, '하와이 원주민/다른 태평양 섬 주민 (Native Hawaiian/Other Pacific Islander)'), (5, '백인 (White)')], null=True),
        ),
    ]
