# Generated by Django 3.2.13 on 2023-02-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_image'),
        ('account', '0003_auto_20230212_1751'),
    ]

    operations = [
    ]
