# Generated by Django 3.2.13 on 2023-03-05 11:54

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230213_2209'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserCustomManager()),
            ],
        ),
    ]
