# Generated by Django 3.2.13 on 2023-02-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_image'),
        ('account', '0004_alter_user_ethnicity'),
    ]

    operations = [
    ]
