# Generated by Django 3.2.13 on 2023-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_20230226_1557'),
        ('account', '0005_merge_20230212_1323'),
    ]

    operations = [
    ]
