# Generated by Django 3.2.13 on 2023-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20230305_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dormant',
            field=models.BooleanField(default=False),
        ),
    ]
