# Generated by Django 3.2.13 on 2023-03-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_managers'),
        ('account', '0006_merge_20230305_1613'),
    ]

    operations = [
    ]
