# Generated by Django 3.2.13 on 2023-03-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_username'),
        ('account', '0006_merge_20230305_1613'),
    ]

    operations = [
    ]
