# Generated by Django 3.2.13 on 2023-04-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20230312_1722'),
        ('account', '0007_user_is_dormant'),
    ]

    operations = [
    ]
