# Generated by Django 3.2.13 on 2023-04-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20230312_1440'),
        ('account', '0007_merge_20230312_1722'),
    ]

    operations = [
    ]
