# Generated by Django 3.2.13 on 2023-03-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20221211_0656'),
        ('notification', '0002_auto_20230128_1749'),
    ]

    operations = [
    ]
