# Generated by Django 3.1.2 on 2022-07-22 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_report', '0001_initial'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='feed.post'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_report_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['id'], name='content_rep_id_b5407a_idx'),
        ),
    ]
