# Generated by Django 3.1.2 on 2022-08-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('content_report', '0002_auto_20220722_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_report_set', to='feed.post'),
        ),
    ]
