# Generated by Django 3.2.13 on 2023-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20221203_2202'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responserequest',
            name='unique_response_request',
        ),
        migrations.AddConstraint(
            model_name='responserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('requester', 'requestee', 'question'), name='unique_response_request'),
        ),
    ]
