# Generated by Django 3.2.13 on 2022-09-21 13:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.CheckConstraint(check=models.Q(('tagging_user', django.db.models.expressions.F('tagged_user')), _negated=True), name='tagging_user_and_tagged_user_cannot_be_equal'),
        ),
    ]
