# Generated by Django 3.2.13 on 2022-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag', '0002_add_constraint_to_user_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usertag',
            name='unique_user_tag',
        ),
        migrations.RemoveConstraint(
            model_name='usertag',
            name='tagging_user_and_tagged_user_cannot_be_equal',
        ),
        migrations.AddField(
            model_name='usertag',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertag',
            name='offset',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.UniqueConstraint(fields=('tagging_user', 'tagged_user', 'content_type', 'object_id', 'offset'), name='unique_user_tag'),
        ),
    ]
