# Generated by Django 3.2.13 on 2022-11-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag', '0003_auto_20221106_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='username_str',
            field=models.CharField(default='', max_length=20),
        ),
    ]
