name: Deploy project

on:
#  schedule:
#    - cron: '0 6 * * 1'  # At 19:00 on Sunday (KST)
  push:
    branches:
      - feature/issue-196

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build frontend
      run: |
        cd frontend
        yarn install
        yarn run build --prod
        echo "[INFO] Build Frontend Step Done"

    - name: scp artifacts to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        source: "frontend/build"
        target: "~/adoor/frontend/build"

    - name: Restart Nginx service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          sudo systemctl restart nginx.service

    - name: Deploy Backend Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          source ~/venv/bin/activate
          cd /home/ubuntu/adoor
          git checkout main
          git pull
          cd /home/ubuntu/adoor/backend/adoorback
          ./manage.py makemigrations
          ./manage.py migrate
          sudo systemctl restart uwsgi
          echo "[INFO] Backend Deployment Step Done"
