name: Rollback project

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Enter commit SHA to rollback to.'
        required: true
        type: string
      additional_command:
        description: 'Do you have any additional command to apply? ex) ./manage.py update_translation_fields'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.commit }}

    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build frontend
      run: |
        cd frontend
        yarn install
        CI='false' yarn run build --prod
    - name: Remove previous build file
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd /home/ubuntu/adoor/frontend
          rm -r build
    - name: scp artifacts to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        source: "frontend/build"
        target: "~/adoor"

    - name: Restart Nginx service
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          sudo systemctl restart nginx.service

    - name: Deploy Backend Code
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          source ~/venv3.9/bin/activate
          cd /home/ubuntu/adoor
          git checkout main ${{ github.event.inputs.commit }}
          git pull
          cd /home/ubuntu/adoor/backend/adoorback
          pip install -r requirements.txt
          ./manage.py migrate
          ${{ github.event.inputs.additional_command }}
          sudo systemctl restart uwsgi